server:
  port: 9000

spring:
  application:
    name: demo

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
      # create, update, create-drop, none 등의 옵션이 있습니다.
      # create: 기존테이블 삭제 후 다시 생성
      # update: 변경된 부분만 반영
      # create-drop: create와 같으나 종료 시점에 테이블 DROP
      # none: 사용하지 않음
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # DDl 생성 시 데이터베이스 고유의 기능 사용여부
    generate-ddl: false
    # 실행되는 쿼리문 보여주기 여부
    show-sql: true
    properties:
      hibernate:
        format_sql: true



  datasource:
    platform: mysql
    url: jdbc:mysql://asac-spring-database.chqlqtpqa1px.ap-northeast-2.rds.amazonaws.com/demo?autoReconnect=true&setTimezone=Asia/Seoul # 변경해주세요
    username: admin
    password: asacSpring22
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전